- alias: "Evaluate Conditions When AC_input Restarts or Becomes Available & Send Msg"
  trigger:
    - platform: state
      entity_id: switch.sonoff_1001e5d0bf  # AC_input
      to: 'available'
    - platform: state
      entity_id: switch.sonoff_1001e5d0bf
      to: 'off'
  action:
    - service: script.evaluate_conditions_1
    - service: input_number.set_value
      data:
        entity_id: input_number.ac_input_available_timestamp
        value: "{{ utcnow().timestamp() | int }}"

- alias: "Evaluate Conditions When AC_input Becomes Unavailable & Send Msg"
  trigger:
    - platform: state
      entity_id: switch.sonoff_1001e5d0bf  # AC_input
      to: 'unavailable'
  action:  
    - variables:
        last_timestamp: "{{ states('input_number.ac_input_available_timestamp') | float }}"
        current_timestamp: "{{ utcnow().timestamp() | float }}"
        duration: "{{ current_timestamp - last_timestamp }}"
        current_total: "{{ states('input_number.ac_input_total_available_seconds') | float }}"
    - service: input_number.set_value
      data:
        entity_id: input_number.ac_input_total_available_seconds
        value: "{{ (current_total + duration) | int }}"
    - delay: '00:00:05'
    - service: script.evaluate_conditions_2

- alias: "Turn On inverter_to_fridge in the morning if Sun is good"
  trigger:
    - platform: time
      at: "10:30:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.home_hours_of_sun_day_0
      above: 9
    - condition: numeric_state
      entity_id: sensor.home_cloud_cover_day_0
      below: 21
    - condition: numeric_state
      entity_id: sensor.home_solar_irradiance_day_0
      above: 3000
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.sonoff_1001e606c3  # inverter_to_fridge
  mode: single

- alias: "Turn On inverter_to_fridge in the noon if Sun is moderate"
  trigger:
    - platform: time
      at: "13:30:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.home_hours_of_sun_day_0
      above: 5
    - condition: numeric_state
      entity_id: sensor.home_cloud_cover_day_0
      below: 35
    - condition: numeric_state
      entity_id: sensor.home_solar_irradiance_day_0
      above: 3000
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.sonoff_1001e606c3  # inverter_to_fridge
  mode: single

- alias: "Turn Off inverter_to_fridge at night"
  trigger:
    - platform: time
      at: "16:20:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.sonoff_1001e606c3  # inverter_to_fridge
  mode: single

- alias: "Log AC Input Total Available Seconds to CSV every Midnight"
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: shell_command.log_ac_input_total_available_seconds

- alias: "Reset AC Input Total Available Seconds to Zero after Logging"
  trigger:
    platform: time
    at: "00:00:05"  # 5-second delay to ensure logging happens first
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.ac_input_total_available_seconds
        value: 0
