# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

sonoff:
  username: !secret username
  password: !secret password
  mode: auto

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Setting the whatsapp notification service
notify:
  - name: WhatsApp
    platform: rest
    resource: https://api.callmebot.com/whatsapp.php
    data:
      source: HA
#      phone: !secret my_phone_num     # Replace with your phone number
#      apikey: !secret my_api_key      # Replace with your CallMeBot API key

# some helper entities to record time related data
input_number:
  ac_input_available_timestamp:          # record when the AC input becomes available in seconds since epoch
    name: AC Input Available Timestamp
    initial: 0
    min: 0
    max: 2147483647
    step: 1

  ac_input_total_available_seconds:     # holds AC_input total available seconds since last midnight
    name: AC Input Total Available Seconds
    initial: 0
    min: 0
    max: 86400
    step: 1


shell_command:
  log_ac_input_total_available_seconds: >
    bash -c 'echo "{{ now().strftime("%Y-%m-%d") }},{{ states("input_number.ac_input_total_available_seconds") }}" >> /config/ac_input_log.csv'

