

evaluate_conditions_1:
  # When AC_input becomes available, check the status of inverter_to_fridge
  sequence:
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.sonoff_1001e606c3  # inverter_to_fridge
              state: 'on'
          sequence:
            # inverter_to_fridge is ON; cutting all power sources for 10 seconds to allow motor rest.
            - service: switch.turn_off
              target:
                entity_id: switch.sonoff_1001e5d0bf  # AC_input
            - service: switch.turn_off
              target:
                entity_id: switch.sonoff_1001e606c3  # inverter_to_fridge
            - delay: "00:00:10"
            - service: switch.turn_on
              target:
                entity_id: switch.sonoff_1001e5d0bf  # AC_input

    - choose:
        - conditions:
            - condition: state
              entity_id: switch.sonoff_1001e606c3  # inverter_to_fridge
              state: 'off'
          sequence:
            # inverter_to_fridge is OFF; allowing AC_input immediately.
            - service: switch.turn_on
              target:
                entity_id: switch.sonoff_1001e5d0bf  # AC_input


evaluate_conditions_2:
  # When AC_input becomes unavailable, turn the inverter_to_fridge on if in good solar time
  sequence:
    - condition: and
      conditions:
        - condition: time
          after: '10:00:00'
          before: '16:00:00'
        - condition: numeric_state
          entity_id: sensor.home_cloud_cover
          below: 20
    - delay: '00:00:10'
    - service: switch.turn_on
      target:
        entity_id: switch.sonoff_1001e606c3  # inverter_to_fridge



